/**
 * GeneratedTasksList Component
 * Phase 2 Chunk 5 - US3: Habit Detail Shows Generated Tasks
 * Displays tasks generated by a specific habit
 */
'use client';

import { useState, useEffect } from 'react';
import { Task } from '@/types/task';
import { format } from 'date-fns';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api';

interface GeneratedTasksListProps {
  userId: string;
  habitId: string;
}

interface GeneratedTasksResponse {
  tasks: Task[];
  total: number;
  page: number;
  limit: number;
}

export function GeneratedTasksList({ userId, habitId }: GeneratedTasksListProps) {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState<string>('');

  useEffect(() => {
    async function fetchTasks() {
      setLoading(true);
      try {
        const params = new URLSearchParams();
        if (statusFilter) params.append('status', statusFilter);
        const url = `${API_URL}/${userId}/habits/${habitId}/generated-tasks?${params}`;
        const res = await fetch(url, { credentials: 'include' });
        if (res.ok) {
          const data: GeneratedTasksResponse = await res.json();
          setTasks(data.tasks);
          setTotal(data.total);
        }
      } catch {
        // Silently fail — section just stays empty
      } finally {
        setLoading(false);
      }
    }
    fetchTasks();
  }, [userId, habitId, statusFilter]);

  if (loading) {
    return (
      <div className="mt-6">
        <h3 className="text-lg font-semibold text-gray-800 mb-3">Generated Tasks</h3>
        <p className="text-sm text-gray-500">Loading...</p>
      </div>
    );
  }

  return (
    <div className="mt-6">
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-lg font-semibold text-gray-800">
          Generated Tasks ({total})
        </h3>
        <select
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
          className="text-sm border rounded px-2 py-1"
        >
          <option value="">All</option>
          <option value="pending">Pending</option>
          <option value="completed">Completed</option>
        </select>
      </div>

      {tasks.length === 0 ? (
        <p className="text-sm text-gray-500">No generated tasks yet.</p>
      ) : (
        <ul className="space-y-2">
          {tasks.map((task) => (
            <li
              key={task.id}
              className={`flex items-center justify-between p-3 rounded-lg border ${
                task.completed
                  ? 'bg-gray-50 border-gray-200'
                  : 'bg-white border-gray-200'
              }`}
            >
              <div className="flex-1">
                <span className={`text-sm font-medium ${
                  task.completed ? 'text-gray-500 line-through' : 'text-gray-900'
                }`}>
                  {task.title}
                </span>
                {task.due_date && (
                  <span className="ml-2 text-xs text-gray-500">
                    {format(new Date(task.due_date), 'MMM d, yyyy')}
                  </span>
                )}
              </div>
              <span className={`text-xs px-2 py-0.5 rounded-full ${
                task.completed
                  ? 'bg-green-100 text-green-800'
                  : 'bg-yellow-100 text-yellow-800'
              }`}>
                {task.status}
              </span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
